"""Generate the signed-distance-field font atlas for the scope labels.

Font: Roboto Condensed Medium (SIL OFL 1.1), e.g. from the npm package
@fontsource/roboto-condensed (files/roboto-condensed-latin-500-normal.woff,
converted to TTF with fontTools). Output: a C header with an 8-bit SDF atlas
(0.5 = glyph edge, inside > 0.5) and glyph metrics in em units.

    python3 tools/gen-scope-font.py RobotoCondensed-Medium.ttf src/scope-font-atlas.h
    clang-format -i src/scope-font-atlas.h
"""
import sys, numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt

FONT, OUT = sys.argv[1], sys.argv[2]
CHARS = "0123456789%.-+"
EM = 48          # atlas pixels per em
SPREAD = 6       # distance range (atlas px) either side of the edge
UP = 8           # supersampling for the distance computation
font = ImageFont.truetype(FONT, EM * UP)
ascent, descent = font.getmetrics()

glyphs = []
for ch in CHARS:
    l, t, r, b = font.getbbox(ch, anchor="ls")       # hi-res px, relative to pen/baseline (y down)
    pad = SPREAD * UP
    # snap the hi-res box to whole atlas pixels so downsampling is exact
    x0 = (l - pad) // UP * UP; y0 = (t - pad) // UP * UP
    x1 = -(-(r + pad) // UP) * UP; y1 = -(-(b + pad) // UP) * UP
    W, H = x1 - x0, y1 - y0
    img = Image.new("L", (W, H), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
    a = np.asarray(img) >= 128
    d = distance_transform_edt(~a) - distance_transform_edt(a)   # >0 outside, hi-res px
    d = d.reshape(H // UP, UP, W // UP, UP).mean(axis=(1, 3)) / UP  # atlas px
    v = np.clip(0.5 - d / (2 * SPREAD), 0, 1)
    glyphs.append(dict(ch=ch, sdf=(v * 255 + 0.5).astype(np.uint8),
                       x=x0 / UP / EM, y=y0 / UP / EM, adv=font.getlength(ch) / UP / EM))

# shelf-pack into a fixed-width atlas
AW = 256; x = y = row_h = 0
for g in glyphs:
    h, w = g["sdf"].shape
    if x + w > AW:
        x = 0; y += row_h; row_h = 0
    g["ax"], g["ay"] = x, y
    x += w; row_h = max(row_h, h)
AH = y + row_h
atlas = np.zeros((AH, AW), np.uint8)
for g in glyphs:
    h, w = g["sdf"].shape
    atlas[g["ay"]:g["ay"] + h, g["ax"]:g["ax"] + w] = g["sdf"]

with open(OUT, "w") as f:
    f.write("// Generated by tools/gen-scope-font.py - do not edit.\n")
    f.write("// Signed-distance-field atlas of Roboto Condensed Medium (SIL Open Font License 1.1,\n")
    f.write("// see data/fonts/OFL-RobotoCondensed.txt). 0.5 = glyph edge, inside > 0.5.\n#pragma once\n\n")
    f.write(f"#define SCOPE_FONT_ATLAS_W {AW}\n#define SCOPE_FONT_ATLAS_H {AH}\n")
    f.write(f"#define SCOPE_FONT_EM_PX {EM}.0f   // atlas pixels per em\n")
    f.write(f"#define SCOPE_FONT_SPREAD_PX {SPREAD}.0f // SDF range either side of the edge, atlas px\n")
    cap = font.getbbox("0", anchor="ls")[1] / UP / EM
    f.write(f"#define SCOPE_FONT_DIGIT_HEIGHT_EM {-cap:.6f}f // height of digits above the baseline\n\n")
    f.write("struct scope_font_glyph {\n\tchar ch;\n\tunsigned short ax, ay, aw, ah; // atlas rect, px\n"
            "\tfloat x, y;    // top-left of the rect relative to pen position / baseline, em (y down)\n"
            "\tfloat advance; // em\n};\n\n")
    f.write(f"static const struct scope_font_glyph scope_font_glyphs[{len(glyphs)}] = {{\n")
    for g in glyphs:
        h, w = g["sdf"].shape
        ch = "'\\\\'" if g["ch"] == "\\" else f"'{g['ch']}'"
        f.write(f"\t{{{ch}, {g['ax']}, {g['ay']}, {w}, {h}, {g['x']:.6f}f, {g['y']:.6f}f, {g['adv']:.6f}f}},\n")
    f.write("};\n\n")
    f.write(f"static const unsigned char scope_font_atlas[{AW * AH}] = {{\n")
    flat = atlas.flatten()
    for i in range(0, len(flat), 24):
        f.write("\t" + ", ".join(str(v) for v in flat[i:i + 24]) + ",\n")
    f.write("};\n")
print(AW, AH, len(glyphs))
